### ISSUE TITLE
how to used the api

### ISSUE THREAD

**Issue by leeyisoft** [erlware/Erlang-and-OTP-in-Action-Source#5]
run after ok, how to used the api?
I tried and failed : 
3> simple_cache:insert(lee, "leeyi").
...
4> simple_cache:insert(lee, leeyi).  
...
5> simple_cache:insert(lee, 33).   
...
6> simple_cache:insert(lee, [leeyi,dd]).
...
9> simple_cache:insert('lee', 'dd').
** exception error: bad argument
     in function  ets:lookup/2
        called as ets:lookup(sc_store,lee)
     in call from sc_store:lookup/1 (src/sc_store.erl, line 17)
     in call from simple_cache:insert/2 (src/simple_cache.erl, line 8)

**Comment by richcarl** [comment]
It's hard to say from your examples, but something has probably crashed between line 6 and line 9, so that the ets table is no longer available. Can you repeat the failure?

**Comment by leeyisoft** [comment]
I know the problem:
must be executed sc_stoce:init();
