### ISSUE TITLE
Second Edition

### ISSUE THREAD

**Issue by sleeptillseven** [erlware/Erlang-and-OTP-in-Action-Source#6]
Hi,

do you plan to update the book to reflect trends in the community and language?

Thanks,
Chris

**Comment by richcarl** [comment]
We're discussing a second edition, but nothing has been decided yet.

**Comment by sleeptillseven** [comment]
Okay, thanks. Would be great should you decide to update :)

**Comment by ericbmerritt** [comment]
I suspect strongly we will. However, no timelines as yet.
