### ISSUE TITLE
Chapter 6 simple cache error bad_return

### ISSUE THREAD

**Issue by sidwubf** [erlware/Erlang-and-OTP-in-Action-Source#7]
I got this when i run the command "application:start(simple_cache)."
{error,
    {bad_return,
        {{sc_app,start,[normal,[]]},
         {'EXIT',
             {undef,
                 [{sc_app,start,[normal,[]],[]},
                  {application_master,start_it_old,4,
                      [{file,"application_master.erl"},{line,272}]}]}}}}}

=INFO REPORT==== 2-Apr-2015::11:37:28 ===
    application: simple_cache
    exited: {bad_return,
                {{sc_app,start,[normal,[]]},
                 {'EXIT',
                     {undef,
                         [{sc_app,start,[normal,[]],[]},
                          {application_master,start_it_old,4,
                              [{file,"application_master.erl"},
                               {line,272}]}]}}}}
    type: temporary

**Comment by ericbmerritt** [comment]
@sidwubf do you have the app compiled and is the ebin dir in your path?

**Comment by sidwubf** [comment]
Yes, i'm sure

**Comment by ericbmerritt** [comment]
hmm. the problem is that sc_app:start isn't defined. So its erroring out. The most likely cause of that is the beam code is not in erlang's search path for some reason. Can you give me the commands you went through to download, build and run it?

**Comment by sidwubf** [comment]
git clone https://github.com/erlware/Erlang-and-OTP-in-Action-Source.git
cd Erlang-and-OTP-in-Action-Source/chapter_06
erl -pa ebin
Then i got this:
Erlang/OTP 17 [erts-6.3.1] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Eshell V6.3.1  (abort with ^G)
1> application:start(simple_cache).
{error,
    {bad_return,
        {{sc_app,start,[normal,[]]},
         {'EXIT',
             {undef,
                 [{sc_app,start,[normal,[]],[]},
                  {application_master,start_it_old,4,
                      [{file,"application_master.erl"},{line,272}]}]}}}}}

=INFO REPORT==== 7-Apr-2015::12:06:16 ===
    application: simple_cache
    exited: {bad_return,
                {{sc_app,start,[normal,[]]},
                 {'EXIT',
                     {undef,
                         [{sc_app,start,[normal,[]],[]},
                          {application_master,start_it_old,4,
                              [{file,"application_master.erl"},
                               {line,272}]}]}}}}
    type: temporary

**Comment by ericbmerritt** [comment]
Thats the problem then. You didn't actually compile the code. Add the following bits to the command you are executing.
```
git clone https://github.com/erlware/Erlang-and-OTP-in-Action-Source.git
cd Erlang-and-OTP-in-Action-Source/chapter_06
cd simple_cache
erlc -o ./ebin/ src/*
erl -pa ebin
```

The two new pieces are

```
cd simple_cache
erlc -o ./ebin/ src/*
```

**Comment by sidwubf** [comment]
Great, thanks a lot @ericbmerritt
